DJANGO/Incidencias_examen_completo/incidencias/urls.py
from django.urls import path,include
from .views import LineaListView,IncidenciaCreateView,LineaDeleteView,LineaCreateView,EstacionCreateView,IncidenciaListView,LineaUpdateView
from . import views
from rest_framework import routers  

#!API_REST_FRAMEWORK
router=routers.DefaultRouter()

router.register('lineas',views.LineaViewSet)
router.register('estaciones',views.EstacionViewSet)
router.register('incidencias',views.IncidenciaViewSet)


app_name = 'incidencias'
urlpatterns = [
     path('listado/', LineaListView.as_view(),name='listado'),
     path('incidencia/nueva/<int:estacion_id>/', IncidenciaCreateView.as_view(),name='nueva_incidencia'),
     path('linea/nueva/', LineaCreateView.as_view(),name='nueva_linea'),
     path('estacion/nueva/', EstacionCreateView.as_view(),name='nueva_estacion'),
     path('incidencias/', IncidenciaListView.as_view(), name='incidencia_list'),
     path('update/<int:pk>/', LineaUpdateView.as_view(), name='update_linea'),
     path('pareja/<int:pk>/delete/', LineaDeleteView.as_view(), name='delete_linea'),
     path('api/',include(router.urls)),


]

DJANGO/Incidencias_examen_completo/incidencias_examen/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('incidencias.urls')),
    path('docs/',include_docs_urls(title='API Documentación')),
    path('accounts/', include('allauth.urls')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DJANGO/Incidencias_examen_completo/incidencias/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Linea(models.Model):
    nombre = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    distancia=models.FloatField()
    
    def __str__(self) -> str:
       return self.nombre
   
    # @admin.display(boolean=True, ordering='distancia', description='¿Distancia mayor a 100?')
    # def distancia_mayor_a_100(self, obj):
    #     return obj.distancia < 5
    
class Estacion(models.Model):
    nombre= models.CharField(max_length=50)
    linea=models.ForeignKey(Linea,  on_delete=models.CASCADE,related_name="estaciones")

    class Meta:
        verbose_name_plural = "Estaciones"
        
    def __str__(self) ->str:
        return self.nombre
    
class Incidencia(models.Model):
    texto=models.TextField(max_length=50)
    fecha=models.DateField(default=timezone.now)#! default=timezone.now si puede editar    ||||  auto_now_add=True no puede editar la fecha
    estacion=models.ForeignKey(Estacion,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.estacion.nombre} ({self.estacion.linea.nombre} {self.texto } )"


#! ORM SHELL

#! CREAR OBJETOS
# # Crear una nueva Linea
# linea = Linea.objects.create(nombre="Linea 1", color="Azul", distancia=10.5)

# # Crear una nueva Estacion asociada a la Linea que acabamos de crear
# estacion = Estacion.objects.create(nombre="Estacion 1", linea=linea)

# # Crear una nueva Incidencia asociada a la Estacion que acabamos de crear
# incidencia = Incidencia.objects.create(texto="Incidencia 1", estacion=estacion)



# # Obtener un objeto por su ID
# linea = Linea.objects.get(id=1)

# # Obtener un objeto por un campo que no es la ID
# linea = Linea.objects.get(nombre="Linea 1")

# # Obtener todos los objetos que cumplen con un criterio
# lineas_rojas = Linea.objects.filter(color="Rojo")

# # Ordenar los objetos por un campo
# lineas_ordenadas = Linea.objects.order_by('distancia')

# # Excluir objetos que cumplen con un criterio
# lineas_no_rojas = Linea.objects.exclude(color="Rojo")

# # Actualizar campos de un objeto
# linea.color = "Azul"
# linea.save()

# # Actualizar campos de varios objetos a la vez
# Linea.objects.filter(color="Rojo").update(color="Azul")

# # Eliminar un objeto
# linea.delete()

# # Eliminar varios objetos a la vez
# Linea.objects.filter(color="Azul").delete()


#! ORM DEL TUTORIAL DE DJANGO>>> from polls.models import Choice, Question  # Import the model classes we just wrote.

# # No questions are in the system yet.
# >>> Question.objects.all()
# <QuerySet []>

# # Create a new Question.
# # Support for time zones is enabled in the default settings file, so
# # Django expects a datetime with tzinfo for pub_date. Use timezone.now()
# # instead of datetime.datetime.now() and it will do the right thing.
# >>> from django.utils import timezone
# >>> q = Question(question_text="What's new?", pub_date=timezone.now())

# # Save the object into the database. You have to call save() explicitly.
# >>> q.save()

# # Now it has an ID.
# >>> q.id
# 1

# # Access model field values via Python attributes.
# >>> q.question_text
# "What's new?"
# >>> q.pub_date
# datetime.datetime(2012, 2, 26, 13, 0, 0, 775217, tzinfo=datetime.timezone.utc)

# # Change values by changing the attributes, then calling save().
# >>> q.question_text = "What's up?"
# >>> q.save()

# # objects.all() displays all the questions in the database.
# >>> Question.objects.all()
# <QuerySet [<Question: Question object (1)>]>




# # Make sure our __str__() addition worked.
# >>> Question.objects.all()
# <QuerySet [<Question: What's up?>]>

# # Django provides a rich database lookup API that's entirely driven by
# # keyword arguments.
# >>> Question.objects.filter(id=1)
# <QuerySet [<Question: What's up?>]>
# >>> Question.objects.filter(question_text__startswith="What")
# <QuerySet [<Question: What's up?>]>

# # Get the question that was published this year.
# >>> from django.utils import timezone
# >>> current_year = timezone.now().year
# >>> Question.objects.get(pub_date__year=current_year)
# <Question: What's up?>


#! uso del incidencias_set.all() 
#  q = Question.objects.get(pk=1)

# # Display any choices from the related object set -- none so far.
# >>> q.choice_set.all()
# <QuerySet []>

# # Create three choices.
# >>> q.choice_set.create(choice_text="Not much", votes=0)
# <Choice: Not much>
# >>> q.choice_set.create(choice_text="The sky", votes=0)
# <Choice: The sky>
# >>> c = q.choice_set.create(choice_text="Just hacking again", votes=0)

# # Choice objects have API access to their related Question objects.
# >>> c.question
# <Question: What's up?>

# # And vice versa: Question objects get access to Choice objects.
# >>> q.choice_set.all()
# <QuerySet [<Choice: Not much>, <Choice: The sky>, <Choice: Just hacking again>]>
# >>> q.choice_set.count()
# 3


#! para personalizar el admin con el @admin
# from django.contrib import admin


# class Question(models.Model):
#     # ...
#     @admin.display(
#         boolean=True,
#         ordering="pub_date",
#         description="Published recently?",
#     )
#     def was_published_recently(self):
#         now = timezone.now()
#         return now - datetime.timedelta(days=1) <= self.pub_date <= now

DJANGO/Incidencias_examen_completo/incidencias/forms.py
from django import forms
from .models import Linea

class LineaForm(forms.ModelForm):
    nombre = forms.CharField(max_length=200, required=True)
    color = forms.CharField(max_length=200, required=True)
    distancia = forms.FloatField(required=True)

    class Meta:
        model = Linea
        fields = ['nombre', 'color', 'distancia']

DJANGO/Incidencias_examen_completo/incidencias/views.py
from django import forms
from django.utils import timezone
from django.contrib import messages
from django.urls import reverse
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from .models import Linea,Estacion,Incidencia
from .forms import  LineaForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


#!API_REST_FRAMEWORK
from rest_framework import viewsets
from .serializers import LineaSerializer,EstacionSerializer,IncidenciaSerializer
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated


# Create your views here.

class LineaListView(LoginRequiredMixin,ListView):
    model=Linea
    template_name = 'listaLinea.html'
    context_object_name= 'lineas'


#! Esta clase y la de arriba hacen lo mismo pero desde diferente modelo
# class LineaListView(ListView):
#     model = Estacion
#     template_name = 'listaLinea.html'
#     context_object_name = 'estaciones'

    
class IncidenciaListView(LoginRequiredMixin,ListView):
    model=Incidencia
    template_name = 'incidencia_list.html'
    context_object_name= 'incidencias'
    
    
    
# class LineaCreateView(CreateView):
#     model= Linea
#     template_name='linea_form.html'
#     fields= '__all__'
#     success_url= '/listado/'
    
#     def form_valid(self, form):
#         response = super().form_valid(form)
#         messages.success(self.request, "La línea ha sido creada con éxito.")
#         return response

#     def get_success_url(self):
#         return reverse('incidencias:listado')
    
#! Más fácil que la de arriba para mandar mensaje de exito (hay que crear el forms.py)    
class LineaCreateView(CreateView):
    form_class = LineaForm
    template_name = 'linea_form.html'
    success_url = '/listado/'

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "La línea ha sido creada con éxito.")
        return response    

class EstacionCreateView(CreateView):
    model=Estacion
    template_name='estacion_form.html'
    fields= '__all__'
    success_url = '/listado/'

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "La estación ha sido creada con éxito.")
        return response
    
    
class IncidenciaCreateView(CreateView):
    model = Incidencia
    # fields = ['texto']
    fields = ['texto', 'estacion', 'fecha']
    template_name = 'incidencia_form.html'

    #!Esta forma es para cuando se hace el create sin enviar nada por la url 
    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #     messages.success(self.request, "La incidencia ha sido creada con éxito.")
    #     return response
    
    # #!Hacer el input fecha como type date
    # def get_form(self, form_class=None):
    #     form = super().get_form(form_class)
    #     form.fields['fecha'].widget = forms.DateInput(attrs={'type': 'date'})
    #     return form
    
    #!Esta forma es para cuando se hace el create enviando el id por la url 
    def form_valid(self, form):
        estacion_id = self.kwargs.get('estacion_id')
        if estacion_id:
            form.instance.estacion = Estacion.objects.get(id=estacion_id)
        form.instance.fecha = timezone.now()
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, "Su incidencia ha sido dada de alta.")
        return reverse('incidencias:incidencia_list')
    
    
class LineaUpdateView(UpdateView):
    model= Linea
    template_name='linea_form.html'
    fields= '__all__'
    success_url= '/listado/'
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "La línea ha sido actualizada con éxito.")
        return response    
    
class LineaDeleteView(DeleteView):
    model= Linea
    template_name='linea_confirm_delete.html'
    success_url= '/listado/'
    
    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(self.request, "La línea ha sido eliminada con éxito.")
        return response    
    
    
#! PARTE DE LA API_REST_FRAMEWORK

class LineaViewSet(viewsets.ModelViewSet):
    queryset = Linea.objects.all()
    serializer_class = LineaSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    
class EstacionViewSet(viewsets.ModelViewSet):
    queryset = Estacion.objects.all()
    serializer_class = EstacionSerializer
    
class IncidenciaViewSet(viewsets.ModelViewSet):
    queryset = Incidencia.objects.all()
    serializer_class = IncidenciaSerializer
   
    

DJANGO/Incidencias_examen_completo/incidencias/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Incidencias</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'incidencias/css/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'incidencias:listado' %}">Listado de Líneas</a></li>
            <li><a href="{% url 'incidencias:nueva_linea' %}">Nueva Línea</a></li>
            <li><a href="{% url 'incidencias:nueva_estacion' %}">Nueva Estación</a></li>
            <li><a href="{% url 'incidencias:incidencia_list' %}">Lista de Incidencias</a></li>
            <li><a href="{% url 'account_logout' %}">cerrar sesion</a></li>
        </ul>
    </nav>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

DJANGO/Incidencias_examen_completo/incidencias/templates/estacion_form.html
{% extends 'base.html' %}
{% block content %}
  <h2>Nueva Estación</h2>
  {% for message in messages %}
    <div class="{{ message.tags }}">{{ message }}</div>
  {% endfor %}
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br />
        {{ field }}
        {% if field.errors %}
          <strong class="error">{{ field.errors.as_text }}</strong>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Guardar</button>
  </form>
{% endblock %} 

DJANGO/Incidencias_examen_completo/incidencias/templates/incidencia_form.html
{% extends 'base.html' %}
{% block content %}
  <h2>Nueva Incidencia</h2>
  {% for message in messages %}
  <div class="{{ message.tags }}">{{ message }}</div>
{% endfor %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

DJANGO/Incidencias_examen_completo/incidencias/templates/incidencia_list.html
{% extends 'base.html' %}
{% block content %}
  {% for message in messages %}
    <div class="{{ message.tags }}">{{ message }}</div>
  {% endfor %}
  <h2>Incidencias</h2>
  <table>
    <tr>
      <th>Fecha</th>
      <th>Texto</th>
      <th>Estación</th>
      <th>Línea</th>
    </tr>
    {% for incidencia in incidencias %}
      <tr>
        <td>{{ incidencia.fecha }}</td>
        <td>{{ incidencia.texto }}</td>
        <td>{{ incidencia.estacion.nombre }}</td>
        <td>{{ incidencia.estacion.linea.nombre }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

DJANGO/Incidencias_examen_completo/incidencias/templates/linea_confirm_delete.html
{% extends "base.html" %}

{% block content  %}

<h1>Eliminar Linea</h1>
<p>¿Estás seguro de que quieres eliminar la linea "{{ object }}"?</p>
<form method="POST">
  {% csrf_token %}
  <input type="submit" value="Confirmar">
</form>
<a href="{% url 'incidencias:listado' %}">Cancelar</a>




{% endblock content  %}

DJANGO/Incidencias_examen_completo/incidencias/templates/linea_form.html
{% extends 'base.html' %}
 {% comment %} {% block content %}
<style>
  .error{
    color:red;
  }
</style>
  <h2>Nueva Linea</h2>
  {% for message in messages %}
    <div class="{{ message.tags }}">{{ message }}</div>
  {% endfor %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Guardar</button>
  </form>
{% endblock %}   {% endcomment %}

 {% block content %}
<style>
  .error{
    color:red;
  }
</style>
  <h2>Nueva Línea</h2>
  {% for message in messages %}
    <div class="{{ message.tags }}">{{ message }}</div>
  {% endfor %}
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br />
        {{ field }}
        {% if field.errors %}
          <strong class="error">{{ field.errors.as_text }}</strong>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Guardar</button>
  </form>
{% endblock %} 

DJANGO/Incidencias_examen_completo/incidencias/templates/listaLinea.html
{% extends 'base.html' %}

{% block content %}
  <h2>Listado de Líneas y Estaciones</h2>
  {% for message in messages %}
    <div class="{{ message.tags }}">{{ message }}</div>
  {% endfor %}
  {% for linea in lineas %}
    <h3><a href="{% url 'incidencias:update_linea' linea.id  %}">{{ linea.nombre }}</a></h3> 
    <a href="{% url 'incidencias:delete_linea' linea.id  %}">Borrar {{ linea.nombre }}</a>
    {% for estacion in linea.estaciones.all %}
      <p>
        {{ estacion.nombre }}
        <a href="{% url 'incidencias:nueva_incidencia' estacion.id %}">+ nueva incidencia</a>
      </p>
    {% endfor %}
  {% endfor %}
{% endblock %} 

{% comment %} {% block content %}
  <h2>Listado de Estaciones</h2>
  {% for message in messages %}
    <div class="{{ message.tags }}">{{ message }}</div>
  {% endfor %}
  {% for estacion in estaciones %}
    <p>
      {{ estacion.nombre }} (Línea: {{ estacion.linea.nombre }})
      <a href="{% url 'incidencias:nueva_incidencia' estacion.id %}">+ nueva incidencia</a>
    </p>
  {% endfor %}
{% endblock %} {% endcomment %}