Repaso Examen DWES/Examen 2ºT/Ejercicio_1/examen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('incidencias.urls')),
]

Repaso Examen DWES/Examen 2ºT/Ejercicio_1/incidencias/urls.py
from django.urls import path, include
from .views import ListadoLineasEstaciones, CreateIncidencia

app_name = 'incidencias'
urlpatterns = [
  path('listado/', ListadoLineasEstaciones.as_view(), name='listado'),
  path('anadir/<int:linea_id>/<int:estacion_id>/', CreateIncidencia.as_view(), name='anadir'),

]

Repaso Examen DWES/Examen 2ºT/Ejercicio_1/incidencias/models.py
from django.db import models

# Create your models here.

class LineaMetro(models.Model):
  nombre = models.CharField(max_length=100)
  color = models.CharField(max_length=100)
  distancia = models.FloatField()

  def __str__(self):
    return self.nombre

class Estacion(models.Model):
  nombre = models.CharField(max_length=100)
  linea = models.ForeignKey(LineaMetro, on_delete=models.CASCADE)

  def __str__(self):
      return self.nombre

class Incidencia(models.Model):
  texto = models.TextField()
  fecha = models.DateField()
  estacion = models.ForeignKey(Estacion, on_delete=models.CASCADE)

  def __str__(self):
      return f'{self.estacion.nombre}({self.estacion.linea.nombre}), {self.texto}'

Repaso Examen DWES/Examen 2ºT/Ejercicio_1/incidencias/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import Estacion, Incidencia
# from django.urls import reverse_lazy

# Create your views here.

class ListadoLineasEstaciones(ListView):
  model = Estacion
  template_name = 'incidencias/listado.html'
  context_object_name = 'estaciones'

class CreateIncidencia(CreateView):
  model = Incidencia
  fields = ['texto', 'fecha']
  template_name = 'incidencias/anadir.html'
  context_object_name = 'estacion'

  #! FUMADA
  # def form_valid(self, form):
  #       linea_id = self.kwargs['linea_id']
  #       estacion_id = self.kwargs['estacion_id']
  #       incidencia = Incidencia.objects.create(
  #           texto=form.cleaned_data['texto'],
  #           fecha=form.cleaned_data['fecha'],
  #           estacion_id=estacion_id
  #       )

  #       # Agregar mensaje de éxito

  #       return super().form_valid(form)

  # def get_success_url(self):
  #       return reverse_lazy('tu_lista_de_incidencias')

Repaso Examen DWES/Examen 2ºT/Ejercicio_1/incidencias/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Listado Linea Metro</title>
  </head>
  <body>
    <h1>App Metro</h1>
    {% block content %}

    {% endblock %}
  </body>
</html>

Repaso Examen DWES/Examen 2ºT/Ejercicio_1/incidencias/templates/incidencias/anadir.html
{% extends 'base.html' %}

{% block content %}
  <h1>Nueva incidencia {{ estacion.nombre }}</h1>
  <form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Enviar</button>
  </form>
{% endblock %}

Repaso Examen DWES/Examen 2ºT/Ejercicio_1/incidencias/templates/incidencias/listado.html
{% extends 'base.html' %}

{% block content %}
  <ul>
    {% for estacion in estaciones %}
      <li>
        {{ estacion.linea.nombre }} - {{ estacion.nombre }} <a href="{% url 'incidencias:anadir' estacion.linea.id estacion.id %}">Nueva incidencia</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}