DJANGO/Django-Pinguinos/apadrina/urls.py
from django.urls import path, include
from .views import Listado, Detalle, logout_view, PinguinoViewSet

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'pinguinos', PinguinoViewSet, 'pinguinos')

app_name = 'apadrina'
urlpatterns = [
  path('', Listado.as_view(), name='index'),
  path('<int:pk>/', Detalle.as_view(), name='detalle'),
  path('logout/', logout_view, name='logout'),
  path('api/', include(router.urls)),
]

DJANGO/Django-Pinguinos/pinguinos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
# from django.contrib.auth.views import LogoutView

from . import settings
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apadrina.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('docs/', include_docs_urls(title='Pinguinos API', public=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJANGO/Django-Pinguinos/apadrina/models.py
from django.db import models
# Create your models here.

class Pinguino(models.Model):
  nombre = models.CharField(max_length=100)
  descripcion = models.TextField()
  adoptado = models.BooleanField(default=False)
  imagen = models.ImageField(upload_to='fotos')

  def __str__(self) -> str:
    return self.nombre

DJANGO/Django-Pinguinos/apadrina/views.py
from apadrina.models import Pinguino
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework import permissions, viewsets
from .serializers import PinguinoSerializer

# Create your views here.
logout_view = LogoutView.as_view()

class Listado(ListView):
  model = Pinguino
  template_name = 'apadrina/listado.html'
  paginate_by = 2

class Detalle(LoginRequiredMixin,DetailView):
  model = Pinguino
  template_name = 'apadrina/detalle.html'

class PinguinoViewSet(viewsets.ModelViewSet):
  queryset = Pinguino.objects.all().order_by('nombre')
  serializer_class = PinguinoSerializer
  permission_classes = [permissions.IsAuthenticated]

DJANGO/Django-Pinguinos/apadrina/templates/apadrina/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      Pingüinos -{% block title %}

      {% endblock %}
    </title>
  </head>
  <body>
    {% if user.is_authenticated %}
      {{ user }} <form action="{% url 'logout' %}" method="post">
        {% csrf_token %} <input type="submit" value="Cerrar sesión" name="logout" />
      </form>
    {% else %}
      <a href="{% url 'login' %}">Iniciar sesión</a>
    {% endif %}
    {% block content %}

    {% endblock %}
  </body>
</html>

DJANGO/Django-Pinguinos/apadrina/templates/apadrina/detalle.html
{% extends 'apadrina/base.html' %}

{% block title %}
  {{ object.nombre }}
{% endblock %}

{% block content %}
  <h1>{{ object.nombre }} {{ object.adoptado|yesno:':),:(,-' }}</h1>
  <p>
    Adoptado:<input type="checkbox" value="" {{ object.adoptado|yesno:'checked,,' }} />
  </p>
  <p>{{ object.descripcion }}</p>
  <img src="{{ object.imagen.url }}" alt="" />
{% endblock %}

DJANGO/Django-Pinguinos/apadrina/templates/apadrina/listado.html
{% extends 'apadrina/base.html' %}

{% block title %}
  Listado de Pingüinos
{% endblock %}
{% block content %}
  <ul>
    {% for object in object_list %}
      <li>
        <a href="{% url 'apadrina:detalle' object.pk %}">{{ object }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}