Repaso Examen DWES/Examen Ordinaria/Ejercicio_3/parejas/urls.py
from django.urls import path
from .views import ListadoParejas, DetallePersona

app_name = 'parejas'
urlpatterns = [
  path('listado', ListadoParejas.as_view(), name='listado'),
  path('detalle/<int:pk>', DetallePersona.as_view(), name='detalle'),
]

Repaso Examen DWES/Examen Ordinaria/Ejercicio_3/registro_civil/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parejas.urls')),
]

Repaso Examen DWES/Examen Ordinaria/Ejercicio_3/parejas/models.py
from django.db import models

class Persona(models.Model):
  nombre = models.CharField(max_length=50)
  apellido1 = models.CharField(max_length=50)
  apellido2 = models.CharField(max_length=50)
  descripcion = models.TextField()

  def __str__(self):
    return self.nombre

class Pareja(models.Model):
  persona1 = models.ForeignKey(Persona, on_delete=models.CASCADE, related_name="persona1")
  persona2 = models.ForeignKey(Persona, on_delete=models.CASCADE, related_name="persona2")
  fecha_inicio = models.DateField()
  lugar = models.CharField(max_length=50)

  def __str__(self):
    return f'{self.persona1.apellido1}, {self.persona2.apellido1} ({self.fecha_inicio})'

Repaso Examen DWES/Examen Ordinaria/Ejercicio_3/parejas/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Pareja, Persona

# Create your views here.

class ListadoParejas(ListView):
  model = Pareja
  template_name = 'parejas/listado.html'
  context_object_name = 'parejas'

class DetallePersona(DetailView):
  model = Persona
  template_name = 'parejas/detalle.html'
  context_object_name = 'persona'

Repaso Examen DWES/Examen Ordinaria/Ejercicio_3/parejas/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Parejas Django
      {% endblock %}
    </title>
  </head>
  <body>
    <h1>Web de parejas</h1>
    {% block content %}

    {% endblock %}
  </body>
</html>

Repaso Examen DWES/Examen Ordinaria/Ejercicio_3/parejas/templates/parejas/detalle.html
{% extends 'base.html' %}
{% block title %}
  Detalle de {{ persona.nombre }}
{% endblock %}

{% block content %}
  <h1>{{ persona.nombre }} {{ persona.apellido1 }} {{ persona.apellido2 }}</h1>
  <h1>Descripción</h1>
  <p>{{ persona.descripcion }}</p>
{% endblock %}

Repaso Examen DWES/Examen Ordinaria/Ejercicio_3/parejas/templates/parejas/listado.html
{% extends 'base.html' %}

{% block content %}
  <table>
    <thead>
      <tr>
        <th>Apellido pareja</th>
        <th>Lugar</th>
        <th>Fecha</th>
      </tr>
    </thead>
    <tbody>
      {% for pareja in parejas %}
        <tr>
          <td>
            <a href="{% url 'parejas:detalle' pareja.persona1.id %}">{{ pareja.persona1.apellido1 }}</a>
            ,
            <a href="{% url 'parejas:detalle' pareja.persona2.id %}">{{ pareja.persona2.apellido1 }}</a>
          </td>
          <td>{{ pareja.lugar }}</td>
          <td>{{ pareja.fecha_inicio }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}